name: CI

on: [ 'pull_request', 'push']

jobs:
  test:
    name: Test on JDK ${{matrix.java-version}}
    strategy:
      matrix:
        java-version: ["1.8", "11", "13"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Run tests
        run: mvn verify -B
  mutation-testing:
    name: Mutation testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Run mutation testing
        run: mvn test-compile org.pitest:pitest-maven:mutationCoverage -B
