name: CI

on:
  push:
    branches: [master]
    tags: ['v*']
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  test:
    name: Test on JDK ${{matrix.java-version}}
    strategy:
      matrix:
        java-version: ['11', '17', '21']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Run tests
        run: mvn verify -B --no-transfer-progress
  mutation-testing:
    name: Mutation testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run mutation testing
        run: mvn test-compile org.pitest:pitest-maven:mutationCoverage -B --no-transfer-progress
