name: CI

on: [ 'pull_request', 'push']

jobs:
  test:
    name: Test on JDK ${{matrix.java-version}}
    strategy:
      matrix:
        java-version: ["11", "17"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.9.0
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Run tests
        run: mvn verify -B
  mutation-testing:
    name: Mutation testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.9.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run mutation testing
        run: mvn test-compile org.pitest:pitest-maven:mutationCoverage -B
